name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Install npm v8
        run: npm i -g npm@8

      - name: Check code-style
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          prettier_options: --check **/*.{md,yml}
